# Generated by Django 6.0.6 on 2026-06-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('state_origin', models.CharField(max_length=100)),
                ('state_residence', models.CharField(max_length=100)),
                ('relationship_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Relationship', 'In a Relationship')], max_length=30)),
                ('show_phone', models.BooleanField(default=False)),
                ('show_relationship', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
