# Generated by Django 6.0.6 on 2026-07-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
